export const CLEAR_QUESTION = "CLEAR_QUESTION";
export const CLEAR_REDIRECT_TO_QUESTION = "CLEAR_REDIRECT_TO_QUESTION";
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";
export const LOAD_QUESTION_SUCCESS = "LOAD_QUESTION_SUCCESS";
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";
export const CLEAR_ALL_COMMENTS = "CLEAR_ALL_COMMENTS";
export const SAVE_COMMENT_ON_QUESTION_SUCCESS =
  "SAVE_COMMENT_ON_QUESTION_SUCCESS";
export const EDIT_COMMENT_ON_QUESTION_SUCCESS =
  "EDIT_COMMENT_ON_QUESTION_SUCCESS";
export const LOAD_COMMENT_ON_QUESTION_SUCCESS =
  "LOAD_COMMENT_ON_QUESTION_SUCCESS";
export const SAVE_COMMENT_ON_ANSWERS_SUCCESS =
  "SAVE_COMMENT_ON_ANSWERS_SUCCESS";
export const EDIT_COMMENT_ON_ANSWERS_SUCCESS =
  "EDIT_COMMENT_ON_ANSWERS_SUCCESS";
export const LOAD_COMMENT_ON_ANSWERS_SUCCESS =
  "LOAD_COMMENT_ON_ANSWERS_SUCCESS";
export const CLEAR_ANSWERS_SUCCESS = "CLEAR_ANSWERS_SUCCESS";
export const SAVE_ANSWERS_SUCCESS = "SAVE_ANSWERS_SUCCESS";
export const LOAD_ANSWERS_SUCCESS = "LOAD_ANSWERS_SUCCESS";
export const EDIT_ANSWERS_SUCCESS = "EDIT_ANSWERS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
