export const CLEAR_QUESTION = "CLEAR_QUESTION";
export const SAVE_QUESTION_SUCCESS = "SAVE_QUESTION_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
