version: '3.4'

services:
  reverseproxy:
    ports:
      - "44395:443"
  stackunderflow.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
    ports:
      - "7000:7000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  stackunderflow.seq:
    ports:
      - "5341:80"
