CREATE TABLE "LimitsKeyValuePairs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "LimitKey" text NULL,
    "LimitValue" integer NOT NULL,
    CONSTRAINT "PK_LimitsKeyValuePairs" PRIMARY KEY ("Id")
);
